---
- name: Quick group_vars via file in project testing
  hosts: all
  gather_facts: false
  tasks:
    - name: Show variable from group_vars file
      asible.builtin.debug:
        # msg: "The value of my_variable is {{ my_variable }}"
        var: hostvars.inventory_hostname.taco