---
- name: Playbook to monitor packages in a repository and alert when there's a new package
  hosts: Greg-bridge-monitor
  gather_facts: false
  vars:
    # Where will the package files be stored
    file_location: /root

    # Email settings
    email_subject: Bridge Repository Package Version Change
    email_host: relay.gregsowell.com
    email_from: system@gregsowell.com
    email_to: greg@gregsowell.com

  tasks:
    - name: Run yum makecache fast to update repo cache
      ansible.builtin.shell: "yum makecache fast"

    - name: Use yum shell command to get a list of all packages in a specific repository
      # ansible.builtin.shell: "yum list available | tail -n +3 | awk '{if ($3 ~ /ciq-bridge/) print $0}' > {{ file_location }}/available-packages-temp.txt"
      ansible.builtin.shell: "yum list available | tail -n +3 | awk '{if ($3 ~ /ciq-bridge/) print $0}' > {{ file_location }}/available-packages-temp.txt"
      # register: installed_packages
      # changed_when: false

    # - name: Debug installed_packages variable
    #   ansible.builtin.debug:
    #     var: installed_packages.stdout_lines

    - name: Check if available-packages.txt file exists
      ansible.builtin.stat:
        path: "{{ file_location }}/available-packages.txt"
      register: file_check

    - name: Perform block if file_check file doesn't exist
      when: file_check.stat.exists == false
      block:
        - name: Copy available-packages-temp.txt to available-packages.txt
          ansible.builtin.shell: "cp {{ file_location }}/available-packages-temp.txt {{ file_location }}/available-packages.txt"

    - name: Compare available-packages-temp.txt and available-packages.txt
      ansible.builtin.shell: "diff {{ file_location }}/available-packages-temp.txt {{ file_location }}/available-packages.txt"
      register: package_change
      changed_when: false
      failed_when: package_change.rc != 1 and package_change.rc != 0

    - name: Debug package_change variable
      ansible.builtin.debug:
        var: package_change

    - name: Block to process when package_change is not empty
      when: package_change.stdout | default("") != ""
      block:
        - name: Delete the old changelog.txt file
          ansible.builtin.file:
            path: "{{ file_location }}/changelog.txt"
            state: absent

        - name: Issue the yum changelog on changed packages
          when: "'<' in item"
          vars:
            # package_name: "{{ (item | regex_search('< ([^\\.]*)\\.', '\\1') | default(['']))[0] }}"
            package_name: "{{ item | regex_search('< ([^\\.]+)', '\\1') | default('') }}"
          ansible.builtin.shell: "yum changelog {{ package_name }}"
          loop: "{{ package_change.stdout_lines }}"
          ignore_errors: true
          register: changelog_output

        - name: Debug changelog_output variable
          ansible.builtin.debug:
            var: changelog_output

        - name: Create the changelog variable
          when: item.changed == true
          set_fact:
            changelog: "{{ changelog | default('') + item.stdout | default('no valid data') | regex_replace('(?s)^.*?(={4,}.*\n)', '\\1') }} \n\n"
          loop: "{{ changelog_output.results }}"
          
        - name: Write contents of changelog with changes to a file
          ansible.builtin.copy:
            content: "{{ changelog }}"
            dest: "{{ file_location }}/changelog.txt"

        - name: Copy package files from remote host to localhost
          ansible.builtin.fetch:
            src: "{{ item }}"
            dest: "{{ playbook_dir }}/"
            flat: yes
          loop: 
            - "{{ file_location }}/available-packages-temp.txt"
            - "{{ file_location }}/available-packages.txt"
            - "{{ file_location }}/changelog.txt"

        - name: Copy available-packages-temp.txt to available-packages.txt
          ansible.builtin.copy:
            src: "{{ file_location }}/available-packages-temp.txt"
            dest: "{{ file_location }}/available-packages.txt"
            force: yes
            remote_src: true

        - name: Send Email
          community.general.mail:
            host: "{{ email_host }}"
            from: "{{ email_from }}"
            port: 25
            to: "{{ email_to }}"
            subject: "{{ email_subject }}"
            # body: "{{ package_change.stdout_lines }}"
            body: "{{ lookup('template', 'email_template.j2') }}"
            attach: 
              - "{{ playbook_dir }}/available-packages-temp.txt"
              # - "{{ playbook_dir }}/available-packages.txt"
              - "{{ playbook_dir }}/changelog.txt"
            subtype: html
          delegate_to: localhost
          run_once: true

    - name: Block to process when there is/are no new packages 
      when: package_change.stdout | default("") == ""
      block:
        - name: Send Email
          community.general.mail:
            host: "{{ email_host }}"
            from: "{{ email_from }}"
            port: 25
            to: "{{ email_to }}"
            subject: "{{ email_subject }} - No Changes"
            # body: "{{ lookup('template', 'email_template.j2') }}"
            # attach: 
            #   - "{{ playbook_dir }}/available-packages-temp.txt"
            #   - "{{ playbook_dir }}/available-packages.txt"
            #   - "{{ playbook_dir }}/changelog.txt"
            # subtype: html
          delegate_to: localhost
          run_once: true