---
- name: List all AAP Gateway users
  hosts: localhost
  gather_facts: false

  vars:
    aap_users_url: "https://ansible.example.com/api/gateway/v1/users/"
    validate_certs: false
    page_size: 200
    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

  tasks:
    - name: Get users
      ansible.builtin.uri:
        url: "{{ aap_users_url }}?page_size={{ page_size }}"
        method: GET
        url_username: "{{ controller_username }}"
        url_password: "{{ controller_password }}"
        force_basic_auth: true
        return_content: true
        status_code: 200
        validate_certs: "{{ validate_certs }}"
        headers:
          Accept: "application/json"
      register: users_resp
      changed_when: false

    - name: Build compact user list
      ansible.builtin.set_fact:
        users_compact: "{{ (users_compact | default([])) + [ {
          'id': item.id,
          'username': item.username,
          'email': item.email | default(''),
          'is_superuser': item.is_superuser | default(false),
          'last_login': item.last_login | default('')
        } ] }}"
      loop: "{{ users_resp.json.results | default([]) }}"
      changed_when: false

    - name: Show users (compact)
      ansible.builtin.debug:
        var: users_compact

    - name: Save users_compact to file
      ansible.builtin.copy:
        content: "{{ users_compact | to_nice_json }}"
        dest: "{{ script_dir }}/aap_users_compact.json"

    - name: Show usernames only
      ansible.builtin.debug:
        msg: "{{ users_compact | map(attribute='username') | list }}"