---
- name: List all AAP Gateway users
  hosts: localhost
  gather_facts: false

  vars:
    aap_users_url: "https://ansible.example.com/api/gateway/v1/users/"
    validate_certs: false
    page_size: 200
    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

  tasks:
    - name: Get users
      ansible.builtin.uri:
        url: "{{ aap_users_url }}?page_size={{ page_size }}"
        method: GET
        url_username: "{{ controller_username }}"
        url_password: "{{ controller_password }}"
        force_basic_auth: true
        return_content: true
        status_code: 200
        validate_certs: "{{ validate_certs }}"
        headers:
          Accept: "application/json"
      register: users_resp
      changed_when: false

    - name: Build compact user list
      ansible.builtin.set_fact:
        users_compact: "{{ (users_compact | default([])) + [ {
          'id': item.id,
          'username': item.username,
          'email': item.email | default(''),
          'is_superuser': item.is_superuser | default(false),
          'last_login': item.last_login | default('')
        } ] }}"
      loop: "{{ users_resp.json.results | default([]) }}"
      changed_when: false

    # - name: Show users (compact)
    #   ansible.builtin.debug:
    #     var: users_compact

    # - name: Save users_compact to file
    #   ansible.builtin.copy:
    #     content: "{{ users_compact | to_nice_json }}"
    #     dest: "{{ playbook_dir }}/aap_users_compact.json"

    # - name: Show usernames only
    #   ansible.builtin.debug:
    #     msg: "{{ users_compact | map(attribute='username') | list }}"

    # - name: Set usernames to exclude from deletion (override with user_exclude_usernames)
    #   ansible.builtin.set_fact:
    #     excluded_usernames: >-
    #       {{
    #         (user_exclude_usernames | default([
    #           'admin',
    #           '_token_service_user'
    #         ])) | unique
    #       }}
    #   changed_when: false

    - name: Set usernames to exclude from deletion (override with user_exclude_usernames)
      ansible.builtin.set_fact:
        excluded_usernames: 
          - admin
          - _token_service_user
      changed_when: false


    - name: Set inactivity window (days)
      ansible.builtin.set_fact:
        inactivity_days: 35
      changed_when: false

    - name: Compute inactivity cutoff epoch (UTC)
      ansible.builtin.set_fact:
        cutoff_epoch: "{{ (now(utc=true).timestamp() | int) - (inactivity_days | int * 86400) }}"
      changed_when: false

    - name: Initialize deletion list
      ansible.builtin.set_fact:
        users_to_delete: []
      changed_when: false

    - name: Build users_to_delete (never logged in OR inactive > 35 days)
      ansible.builtin.set_fact:
        users_to_delete: "{{ users_to_delete + [ item ] }}"
      vars:
        last_login_raw: "{{ item.last_login }}"
        last_login_epoch: >-
          {%- if last_login_raw is none or last_login_raw == '' -%}
          {{ none }}
          {%- elif (last_login_raw | string) is search('\\.') -%}
          {{ (last_login_raw | to_datetime('%Y-%m-%dT%H:%M:%S.%fZ')).timestamp() | int }}
          {%- else -%}
          {{ (last_login_raw | to_datetime('%Y-%m-%dT%H:%M:%SZ')).timestamp() | int }}
          {%- endif -%}
      loop: "{{ users_compact }}"
      loop_control:
        label: "{{ item.username }}"
      when:
        - item.username not in excluded_usernames
        - not (item.is_superuser | bool)
        - last_login_epoch is none or last_login_epoch < cutoff_epoch
      changed_when: false

    - name: Show cleanup summary
      ansible.builtin.debug:
        msg:
          cutoff_epoch: "{{ cutoff_epoch }}"
          excluded_usernames: "{{ excluded_usernames }}"
          delete_count: "{{ users_to_delete | length }}"
          delete_users: "{{ users_to_delete | map(attribute='username') | list }}"

    - name: Safety guard — prevent accidental mass deletion
      ansible.builtin.fail:
        msg: "Refusing to delete ALL users. Something is wrong."
      when:
        - users_to_delete | length == users_compact | length
        - users_compact | length > 0

    - name: Delete selected users (ONLY if do_delete=true)
      ansible.builtin.uri:
        url: "{{ (aap_users_url | regex_replace('/$', '')) }}/{{ item.id }}/"
        method: DELETE
        url_username: "{{ controller_username }}"
        url_password: "{{ controller_password }}"
        force_basic_auth: true
        status_code: [204, 202, 200]
        validate_certs: "{{ validate_certs }}"
        headers:
          Accept: "application/json"
      loop: "{{ users_to_delete }}"
      loop_control:
        label: "{{ item.username }} (id={{ item.id }})"
      when: do_delete | default(false)