---
- name: List all AAP Gateway users
  hosts: localhost
  gather_facts: false

  vars:
    aap_users_url: "https://ansible.example.com/api/gateway/v1/users/"
    validate_certs: false
    page_size: 200

    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

  tasks:
    - name: Get users
      ansible.builtin.uri:
        url: "{{ aap_users_url }}?page_size={{ page_size }}"
        method: GET
        url_username: "{{ controller_username }}"
        url_password: "{{ controller_password }}"
        force_basic_auth: true
        return_content: true
        status_code: 200
        validate_certs: "{{ validate_certs }}"
        headers:
          Accept: "application/json"
      register: users_resp
      changed_when: false

    - name: Show users (compact) - no community.general needed
      ansible.builtin.debug:
        msg: >-
          {{
            users_resp.json.results
            | map('dict2items')
            | list
          }}
      changed_when: false

    - name: Show users (clean compact dicts)
      ansible.builtin.debug:
        msg: >-
          {{
            users_resp.json.results
            | map('extract', {'id':'id','username':'username','email':'email','is_superuser':'is_superuser','last_login':'last_login'})
            | list
          }}