---
- name: List all AAP Gateway users
  hosts: localhost
  gather_facts: false

  vars:
    aap_users_url: "https://ansible.example.com/api/gateway/v1/users/"
    validate_certs: false
    page_size: 200

    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

  tasks:
    - name: Initialize
      ansible.builtin.set_fact:
        next_url: "{{ aap_users_url }}?page_size={{ page_size }}"
        all_users: []

    - name: Keep fetching pages until next_url is empty
      block:
        - name: GET current page
          ansible.builtin.uri:
            url: "{{ next_url }}"
            method: GET
            url_username: "{{ controller_username }}"
            url_password: "{{ controller_password }}"
            force_basic_auth: true
            return_content: true
            status_code: 200
            validate_certs: "{{ validate_certs }}"
            headers:
              Accept: "application/json"
          register: page
          changed_when: false

        - name: Append results and update next_url
          ansible.builtin.set_fact:
            all_users: "{{ all_users + (page.json.results | default([])) }}"
            # Normalize next into a *real* URL string or '' (empty)
            next_url: "{{ page.json.next | default('') | string | trim }}"
      # Re-run this block as long as next_url looks like an actual URL
      until: next_url | length == 0 or next_url == 'None'
      retries: 20
      delay: 0

    - name: Show users (compact)
      ansible.builtin.debug:
        msg: "{{ all_users | json_query('[].{id:id, username:username, email:email, is_superuser:is_superuser, last_login:last_login}') }}"

    - name: Show usernames only
      ansible.builtin.debug:
        msg: "{{ all_users | map(attribute='username') | list }}"