---
- name: Search for stale switchports and create a report
  hosts: nexus9k3
  gather_facts: false
  vars:
  tasks:
    - name: Issue a show interfaces on the switch
      nxos_command:
        commands:
          - 'show int | b Ethernet1/'
      register: interface_status

    - name: Split command output into per-interface blocks
      set_fact:
        interface_blocks: "{{ interface_status.stdout[0] | regex_findall('(?ms)^Ethernet\\S+.*?(?=^Ethernet\\S+|\\Z)') }}"

    - name: Build list of dictionaries for each interface block
      set_fact:
        interface_details: "{{ interface_details | default([]) + [ {
          'interface': item.splitlines()[0].split(' is ')[0],
          'status_line': item.splitlines()[0],
          'block_lines': item.splitlines(),
          'raw_block': item
        } ] }}"
      loop: "{{ interface_blocks }}"

    - name: Display parsed interface dictionaries
      debug:
        var: interface_details