---
- name: demonstrate using surveys with templates
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    file_loc: /usr/games/survey-template.conf

  tasks:
  - name: call the template with our survey info
    template:
      src: survey-template.conf.j2
      dest: "{{ file_loc }}"

  - name: set file contents to variable
    set_fact:
      file_con: "{{ lookup('file', file_loc) }}"

  - name: debug file to screen
    debug:
      var: file_con