---
- name: Collect stale disconnected 1Gbps switch ports
  hosts: nexus9k3
  gather_facts: false
  vars:
    stale_days_threshold: 60
    uplink_interfaces: []
    uplink_description_regex: '(?i)uplink|trunk|core'
    reserved_description_regex: '(?i)^reserved$'
    headers: switch,interface,description,last_link_flapped,disconnected_days
    email_subject: Stale Switch Port Report
    csv_path: /tmp
    csv_filename: stale_switch_ports.csv

  tasks:
    - name: Reset report CSV file on controller
      run_once: true
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ csv_path }}/{{ csv_filename }}"
        state: absent

    - name: Get all interface details
      cisco.nxos.nxos_command:
        commands:
          - show interface
      register: interface_output

    - name: Split interface output into per-interface blocks
      ansible.builtin.set_fact:
        interface_blocks: >-
          {{
            (interface_output.stdout[0] | default(''))
            | regex_findall('(?ms)^\\S+ is .*?(?=^\\S+ is |\\Z)')
          }}

    - name: Add stale disconnected 1G interfaces to report
      when: 
        - interface_blocks | length > 0
        - is_link_not_connected
        - is_one_gig
        - disconnected_days | int > stale_days_threshold | int
        - not is_reserved
        - not is_uplink_interface
        - not is_uplink_description
      vars:
        detail_text: "{{ item }}"
        port_name: "{{ (detail_text | regex_findall('^(\\S+) is', multiline=True) | first | default('')) | trim }}"
        port_description: "{{ (detail_text | regex_findall('Description:\\s*(.+)') | first | default('')) | trim }}"
        last_link_flapped: "{{ (detail_text | regex_findall('Last link flapped\\s+(.+)') | first | default('never')) | lower | trim }}"
        years_down: "{{ (last_link_flapped | regex_findall('(\\d+)\\s*year\\(s\\)') | first | default(0)) | int }}"
        weeks_down: "{{ (last_link_flapped | regex_findall('(\\d+)\\s*week\\(s\\)') | first | default(0)) | int }}"
        days_down: "{{ (last_link_flapped | regex_findall('(\\d+)\\s*day\\(s\\)') | first | default(0)) | int }}"
        hours_down: "{{ (last_link_flapped | regex_findall('(\\d+)\\s*hour\\(s\\)') | first | default(0)) | int }}"
        mins_down: "{{ (last_link_flapped | regex_findall('(\\d+)\\s*min\\(s\\)') | first | default(0)) | int }}"
        disconnected_days: >-
          {{
          99999 if 'never' in last_link_flapped else
          (years_down * 365) + (weeks_down * 7) + days_down +
          ((hours_down / 24) | round(0, 'floor')) +
          ((mins_down / 1440) | round(0, 'floor'))
          }}
        is_link_not_connected: "{{ detail_text is search('\\(Link not connected\\)') }}"
        is_one_gig: "{{ detail_text is search('BW 1000000 Kbit') }}"
        is_reserved: "{{ port_description is search(reserved_description_regex) }}"
        is_uplink_interface: "{{ port_name in uplink_interfaces }}"
        is_uplink_description: "{{ port_description is search(uplink_description_regex) }}"
        action_type: write
        write_line: >-
          {{ inventory_hostname }},{{ port_name }},{{ port_description | replace(',', ';') }},{{ last_link_flapped }},{{ disconnected_days | int }}
      ansible.builtin.include_role:
        name: ansible-report
      loop: "{{ interface_blocks | default([]) }}"

    - name: Check if report CSV exists
      run_once: true
      delegate_to: localhost
      ansible.builtin.stat:
        path: "{{ csv_path }}/{{ csv_filename }}"
      register: report_csv_stat

    # - name: Send stale-port report email
    #   run_once: true
    #   when: report_csv_stat.stat.exists
    #   ansible.builtin.include_role:
    #     name: ansible-report
    #   vars:
    #     action_type: email

    - name: Show when no stale ports were found
      run_once: true
      when: not report_csv_stat.stat.exists
      ansible.builtin.debug:
        msg: No stale 1Gbps disconnected switch ports matched the criteria.
